# Generated by Django 4.1.7 on 2023-03-15 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bbs.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user_name',
            field=models.ManyToManyField(blank=True, to='bbs.user', verbose_name='ユーザー名'),
        ),
    ]
