# Generated by Django 4.1.7 on 2023-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_album_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bbs/topic/photo/', verbose_name='フォト'),
        ),
    ]
