# Generated by Django 4.1.7 on 2023-03-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='user_name',
            field=models.ForeignKey(default='無し', on_delete=django.db.models.deletion.SET_DEFAULT, to='bbs.user', verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default='未分類', on_delete=django.db.models.deletion.CASCADE, to='bbs.category', verbose_name='カテゴリ'),
        ),
    ]
