# Generated by Django 4.1.7 on 2023-03-11 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_topic_user_name_alter_topic_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user_name',
        ),
    ]
