# Generated by Django 4.1.7 on 2023-03-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_topic_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='user_name',
            field=models.ManyToManyField(to='bbs.user', verbose_name='ユーザー名'),
        ),
    ]
