# Generated by Django 4.1.7 on 2023-03-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_remove_topic_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='test_name', max_length=20, verbose_name='ユーザー名'),
            preserve_default=False,
        ),
    ]
