# Generated by Django 4.1.7 on 2023-03-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_remove_topic_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
