# Generated by Django 4.1.7 on 2023-04-16 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('people_num', models.CharField(max_length=25, verbose_name='社員数')),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='GoodCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='いいねした時刻')),
                ('ip', models.GenericIPAddressField(verbose_name='良いねした人のIPアドレス')),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.companyinfo', verbose_name='いいねしたトピック')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='good',
            field=models.ManyToManyField(through='scraping.GoodCompany', to=settings.AUTH_USER_MODEL, verbose_name='良いね'),
        ),
    ]
